name = "wx_gleam"
version = "0.1.0"
target = "erlang"

# Project metadata for Hex publishing and documentation generation
description = "A Gleam library for creating native GUIs using Erlang's wxWidgets (wx) bindings"
licences = ["MIT"]
repository = { type = "github", user = "haruki7049", repo = "wx_gleam" }

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = { path = "./build/packages/gleam_stdlib" }
gleam_erlang = { path = "./build/packages/gleam_erlang" }

[dev-dependencies]
gleeunit = { path = "./build/packages/gleeunit" }
